default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000


development:
  <<: *default
  # adapter: postgresql
  # database: ror_social_scaffold_development
  adapter: sqlite3
  database: db/development.sqlite3
  # host: localhost
  # port: 5433
  # username: apptest
  # password: password1


test:
  <<: *default
  # adapter: postgresql
  # database: ror_social_scaffold_test
  adapter: sqlite3
  database: db/test.sqlite3


production:
  <<: *default
  adapter: postgresql
  database: app_postgres_production
  username: app_postgres
  password: <%= ENV['APP_POSTGRES_DATABASE_PASSWORD'] %>
  # DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
