name:                   Linters

on:                     pull_request

env:
  FORCE_COLOR:          1

jobs:
  rubocop:
    name:               Rubocop
    runs-on:            ubuntu-latest
    steps:
      - uses:           actions/checkout@v2
      - uses:           actions/setup-ruby@v1
        with:
          ruby-version: ">=2.7.x"
      - name:           Setup Rubocop
        run:            |
          bundle update --bundler
          bundle add rubocop || bundle install
          [ -f .rubocop.yml ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/ruby/.rubocop.yml
          bundle exec rubocop -A Gemfile # Fix the Gemfile to avoid sparse errors
      - name:           Rubocop Report
        run:            bundle exec rubocop --color
  stylelint:
    name:               StyleLint
    runs-on:            ubuntu-latest
    steps:
      - uses:           actions/checkout@v2
      - uses:           actions/setup-node@v1
        with:
          node-version: ">=14.x"
      - name:           Setup Stylelint
        run:            |
          npm install --save-dev stylelint stylelint-scss stylelint-config-standard stylelint-csstree-validator
          [ -f .stylelintrc.json ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/ror/.stylelintrc.json
      - name:           Stylelint Report
        run:            npx stylelint "**/*.{css,scss}"
